# Generated by Django 4.1 on 2022-10-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_digital'),
        ('orders', '0007_rename_status_order_complete_remove_order_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'OrderItem', 'verbose_name_plural': 'OrderItems'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': 'ShippingAddress', 'verbose_name_plural': 'ShippingAddresses'},
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('product',)},
        ),
    ]
