# Generated by Django 4.1 on 2022-09-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cutomer_id',
            new_name='customer_id',
        ),
    ]
