# Generated by Django 4.1 on 2022-09-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_rename_cutomer_id_customer_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('email',)},
        ),
    ]
