# Generated by Django 4.1 on 2022-09-05 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_alter_customer_email_alter_profile_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('email',)},
        ),
    ]
